#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

f_dokku_events_install

[[ "$DOKKU_EVENTS" ]] && f_dokku_events_log_pluginhook_call "$(basename $0)" $@

